@TestOn('browser')
library test.all_web_tests;

// Generated by `pub run dart_dev gen-test-runner -d test/ -e Environment.browser --genHtml`

import './link_matcher_test.dart' as link_matcher_test;
import './providers/browser_history_test.dart'
    as providers_browser_history_test;
import './providers/hash_history_test.dart' as providers_hash_history_test;
import './providers/memory_history_test.dart' as providers_memory_history_test;
import './route_handle_test.dart' as route_handle_test;
import './route_view_test.dart' as route_view_test;
import './url_matcher_test.dart' as url_matcher_test;
import './url_template_test.dart' as url_template_test;
import 'package:test/test.dart';

void main() {
  link_matcher_test.main();
  providers_browser_history_test.main();
  providers_hash_history_test.main();
  providers_memory_history_test.main();
  route_handle_test.main();
  route_view_test.main();
  url_matcher_test.main();
  url_template_test.main();
}
