language: dart
sudo: required
addons:
  chrome: stable

dart:
  - 1.24.3
  - 2.0.0

script:
  - dartfmt -n --set-exit-if-changed example lib test
  - dartanalyzer example lib test
  - pub publish --dry-run
  - pub run test -p chrome -p vm --reporter=expanded
  