name: route_hierarchical
version: 0.10.4
description: A client routing library for Dart
authors:
  - Justin Fagnani <justinfagnani@google.com>
  - Pavel Jbanov <pavelj@google.com>
homepage: https://github.com/Workiva/route.dart

environment:
  sdk: '>=1.9.0 <3.0.0'

dependencies:
  logging: ">=0.11.3 <1.0.0"
  uuid: ^1.0.0

dev_dependencies:
  build_runner: ">=0.6.0 <1.0.0"
  build_test: ">=0.9.0 <1.0.0"
  build_web_compilers: ">=0.2.0 <1.0.0"
  dart2_constant: ^1.0.0
  dependency_validator: ^1.2.2
  mockito: ">=2.2.2 <4.0.0"
  test: ">=0.12.34 <2.0.0"
